platform :ios, "8.0"
inhibit_all_warnings!

# 国内使用 pod update --verbose --no-repo-update

target 'ModuleProject' do
  # 网络库
  pod 'XMNetworking','1.0.2'
  # 富文本编辑与显示框架
  pod 'YYText','1.0.7'
  # 高性能的 iOS JSON 模型框架
  pod 'YYModel','1.0.4'
  # 空白页或出错页
  pod 'DZNEmptyDataSet','1.8.1'
  # 轮播图
  pod 'SDCycleScrollView','1.65'
  # 控件布局
  pod 'Masonry','1.0.2'
  # 列表高度缓存
  pod 'UITableView+FDTemplateLayoutCell','1.4'
  # 刷新控件
  pod 'MJRefresh','3.1.12'
  # QR
  pod 'ZXingObjC','3.2.1'
  # 系统Alter封装
  pod 'LBXAlertAction'
  # 选择器
  pod 'STPickerView', '2.0'
  # 图片选择器
  pod 'TZImagePickerController'
  # Core Data 框架
  pod 'MagicalRecord','2.3.2'
  # 设计师颜色库 搭配色
  pod 'ChameleonFramework'

end
